global:
  scrape_interval: 15s  # Default scrape interval.
  evaluation_interval: 15s  # Default evaluation interval for rules.

scrape_configs:
  # Scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  # Scrape Loki metrics
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100

  # Scrape Node Exporter (if you add it later)
  # - job_name: node
  #   static_configs:
  #     - targets:
  #         - localhost:9100
